export const categories = [
    { id: '1', name: 'Favoritos', imageUrl: '/callback.svg' },
    { id: '2', name: 'Lanches', imageUrl: '/callback.svg' },
    { id: '3', name: 'Combos', imageUrl: '/callback.svg' },
    { id: '4', name: 'Massas', imageUrl: '/callback.svg' },
    { id: '5', name: 'Saladas', imageUrl: '/callback.svg' },
    { id: '6', name: 'Porções', imageUrl: '/callback.svg' },
]


export const dishes = [
    {
        id: '1',
        name: 'Combo Burger',
        price: '45',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '2', '3'],
    },
    {
        id: '2',
        name: 'Macarrão com Queijo',
        price: '75',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '4'],
    },
    {
        id: '3',
        name: 'Fritas',
        price: '35',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '6'],
    },
    {
        id: '4',
        name: 'Caesar Salad',
        price: '55',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '5'],
    },
    {
        id: '5',
        name: 'Sanduba Natural',
        price: '25',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '2'],
    },
    {
        id: '6',
        name: 'Lasanha Bolonhesa',
        price: '85',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '4'],
    },
    {
        id: '7',
        name: 'Lasanha Quatro Queijos',
        price: '85',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '4'],
    },
    {
        id: '8',
        name: 'Combo Vegan Burger',
        price: '65',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '2', '3'],
    },
    {
        id: '9',
        name: 'Salada Completa',
        price: '95',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '5'],
    },
    {
        id: '10',
        name: 'Hot Dog Especial',
        price: '35',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '2', '3'],
    },
    {
        id: '11',
        name: 'Salada Especial',
        price: '95',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '5'],
    },
    {
        id: '12',
        name: 'Coxinhas',
        price: '25',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '6'],
    },
    {
        id: '13',
        name: 'Mandioca',
        price: '25',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '6'],
    },
    {
        id: '14',
        name: 'Polenta',
        price: '25',
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit,Lorem ipsum dolor sit amet consectetur adipisicing elit',
        imageUrl: '/callback.svg',
        categories: ['1', '6'],
    },
]